fix: NPE MeLi Publish Processing.
```
===========> PublishingProcessing.process: Cannot invoke "java.util.List.parallelStream()" because the return value of "com.solop.sp034.process.PublishingProcessing.getValidKeys()" is null [48]
java.lang.NullPointerException: Cannot invoke "java.util.List.parallelStream()" because the return value of "com.solop.sp034.process.PublishingProcessing.getValidKeys()" is null
	at com.solop.sp034.process.PublishingProcessing.doIt(PublishingProcessing.java:38)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:177)
```

### Additional context
ref https://github.com/solop-develop/adempiere-solop/issues/2305