fix: NoSuchMethodError: 'ReferenceUtil.getContextColumnNames(java.lang.String)' (#1835)
Caused by: java.lang.NoSuchMethodError: 'java.util.List org.spin.eca56.util.support.documents.ReferenceUtil.getContextColumnNames(java.lang.String)'